#!/bin/sh
set -eu

: "${PUBLIC_BACKEND_URL:=}"
: "${PUBLIC_APP_VERSION:=}"
: "${PUBLIC_COMMIT_SHA:=}"
: "${PUBLIC_REPOSITORY_URL:=}"
: "${PUBLIC_DEPLOYMENT_ENVIRONMENT:=}"
: "${PUBLIC_EMBED_SESSION_HANDSHAKE:=false}"

cat > /usr/share/nginx/html/env.js <<EOF
window.__RDFARCHITECT_CONFIG__ = {
    PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL}",
    PUBLIC_APP_VERSION: "${PUBLIC_APP_VERSION}",
    PUBLIC_COMMIT_SHA: "${PUBLIC_COMMIT_SHA}",
    PUBLIC_REPOSITORY_URL: "${PUBLIC_REPOSITORY_URL}",
    PUBLIC_DEPLOYMENT_ENVIRONMENT: "${PUBLIC_DEPLOYMENT_ENVIRONMENT}",
    PUBLIC_EMBED_SESSION_HANDSHAKE: "${PUBLIC_EMBED_SESSION_HANDSHAKE}",
};
EOF

exec nginx -g "daemon off;"
